config/routes.rb
Rails.application.routes.draw do
  get 'async_operations/index'
  get 'async_operations/status'

  root 'home#index'
  resources :orders
  get  'csv/upload' => 'csv#upload'
  post 'csv/import' => 'csv#import'

  get 'asyncops' => 'async_operations#index'
  get 'asyncops/status/:id' => 'async_operations#status'

  get 'todos', to: 'site#index'
  get 'todos/new', to: 'site#index'
  get 'todos/:id', to: 'site#index'
  get 'todos/:id/edit', to: 'site#index'

  namespace :api do
    resources :todos, only: %i[index show create destroy update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/async_operation.rb
class AsyncOperation < ApplicationRecord
end

app/models/gdc.rb
class Gdc < ApplicationRecord
    self.table_name = 'global_daily_cumulative'
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
    belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
    has_many :line_items, :dependent => :destroy
    accepts_nested_attributes_for :line_items, allow_destroy: true
end

app/models/todo.rb
# frozen_string_literal: true

class Todo < ApplicationRecord
end

app/controllers/api/todos_controller.rb
# frozen_string_literal: true

class Api::TodosController < ApplicationController
  before_action :set_todo, only: %i[show update destroy]

  def index
    @todos = Todo.all
    render json: @todos
  end

  def show
    render json: @todo
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      render json: @todo, status: :created
    else
      render json: @todo.errors, status: :unprocessable_entity
    end
  end

  def update
    if @todo.update(todo_params)
      render json: @todo, status: :ok
    else
      render json: @todo.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @todo.destroy
  end

  private

  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(
      :id, :title, :completed, :created_at, :updated_at
    )
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
  end

app/controllers/async_operations_controller.rb
class AsyncOperationsController < ApplicationController
  def index
    @asyncops = AsyncOperation.all
  end

  def status
    puts "In status action..."
    @id = params[:id]
    @ao = AsyncOperation.find(@id)
    @op_type = @ao.op_type
    @status  = @ao.status
  end
end

app/controllers/csv_controller.rb
class CsvController < ApplicationController
    
    def upload

    end

    def import
        # copy uploaded file app/jobs directory
        FileUtils.cp(File.new(params[:csvfile].tempfile),
                     "#{Rails.root}/app/jobs/global_daily_cumulative.csv")

        # insert async_operations row
        @filename = params[:csvfile].original_filename
        @ao       = AsyncOperation.new(:op_type  => 'Import CSV',
                                       :filename => @filename,
                                       :status   => :enqueued)

        # enqueue the job
        if @ao.save
            ImportGdcJob4.perform_later(id: @ao.id)
        end

        render :ack
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :set_order, only: [:show, :edit, :update, :destroy]

    # GET /orders
    # GET /orders.json
    def index
        @orders = Order.all
    end

    # GET /orders/1
    # GET /orders/1.json
    def show
    end

    # GET /orders/new
    def new
        @order = Order.new
        @order.line_items.build
    end

    # GET /orders/1/edit
    def edit
    end

    # POST /orders
    # POST /orders.json
    def create
        @order = Order.new(order_params)

        respond_to do |format|
            if @order.save
                format.html { redirect_to @order, notice: 'Order was successfully created.' }
                format.json { render :show, status: :created, location: @order }
            else
                format.html { render :new }
                format.json { render json: @order.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /orders/1
    # PATCH/PUT /orders/1.json
    def update
        respond_to do |format|
            if @order.update(order_params)
                if order_params[:line_items_attributes] != nil
                    order_params[:line_items_attributes].each do |la|
                        if la[1].size == 1 && la[1][:id] != nil
                            @order.line_items.destroy(la[1][:id])
                        end
                    end
                end
                format.html { redirect_to @order, notice: 'Order was successfully updated.' }
                format.json { render :show, status: :ok, location: @order }
            else
                format.html { render :edit }
                format.json { render json: @order.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /orders/1
    # DELETE /orders/1.json
    def destroy
        @order.destroy
        respond_to do |format|
            # format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
            redirect_to root_path, status: :see_other
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
        @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
        params.require(:order).permit(:line_items_attributes => [:id, :item, :quantity, :gift_wrap_type]).to_h
    end
end

app/controllers/site_controller.rb
# frozen_string_literal: true

class SiteController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/async_operations_helper.rb
module AsyncOperationsHelper
end

app/helpers/csv_helper.rb
module CsvHelper
end

app/views/async_operations/index.html.erb
<div>
  <h1>AsyncOperations#index</h1>
  <p>Find me in app/views/async_operations/index.html.erb</p>
  <% @asyncops.each do |ao| %>
    <%= ao.id %> <%= ao.op_type %> <%= ao.filename %> <%= ao.status %> <br/>
  <% end %>
</div>

app/views/async_operations/status.html.erb
<div>
  <h1 class="font-bold text-4xl">AsyncOperations#status</h1>
  Job (id = <%= @id %>, type = <%= @op_type %> ) succesfully <%= @status %>.
</div>

app/views/csv/ack.html.erb
<div class="box-content md:box-content">
    <div class="flex justify-center text-justify"><p>CSV file received.</p></div>
    <div class="flex justify-center text-justify"><p>Your file <%= @filename %> has been received and will be processed.</p></div>
    <div class="flex justify-center text-justify"><p>Please check the <a class="text-orange-600" href="/asyncops/status/<%= @ao.id %>">link</a> for latest status.</p></div>
</div>

app/views/csv/upload.html.erb
  <h1>Upload CSV file</h1>
  <div class="grid grid-cols-2 gap-3 md:grid-flow-col auto-cols-fr">
    <%=form_tag csv_import_path, multipart: true, data: { turbo: false } do%>
      <%=file_field_tag :csvfile%>
      <%= button_to "Upload", "/csv/import" %>
    <%end%>
  </div>

app/views/home/index.html.erb
<div class="box-content md:box-content">
    <h1>Mahrasa</h1>
    <div>&nbsp;</div>
    <div>
        <a href="/csv/upload">Upload global_daily_cumulative.csv</a>
    </div>
    <div>
        <a href="/orders/new">Create Order</a>
    </div>
        <div class="flex justify-center text-justify">
        <a href="/todos">Todo Manager</a>
    </div>
</div>

<div id="root"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mahrasa3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400;500;700&family=Roboto:ital,wght@0,300;0,400;0,700;1,400&display=swap"
      rel="stylesheet"
    />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <!-- <body class="h-screen bg-gradient-to-b from-green-200 to-green-500"> -->
  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>
    

app/views/orders/_edit_form.html.erb
<script type="text/javascript">

    function updateSelectValue() {
        this.previousElementSibling.value = this.value;
        this.previousElementSibling.focus();
    }

    function deleteRow(tableID)
    {
    	try
    	{
    		var table = document.getElementById(tableID);
    		var rowCount = table.rows.length;
    		for(var i=0; i<rowCount; i++)
    		{
    			var row = table.rows[i];
    			var chkbox = row.cells[0].childNodes[0];
    			if(null != chkbox && true == chkbox.checked)
    			{
    				table.deleteRow(i);
    				rowCount--;
    				i--;
    			}
    		}
    	}
    	catch(e)
    	{
    		alert(e);
    	}
    }

    var globalLineItemsRowCount = <%= @order.line_items.length+1 %>;
    function addRowToOrders(tableID)
    {
        var table    = document.getElementById(tableID);
    	var rowCount = table.rows.length;
    	var row      = table.insertRow(rowCount);

        var cell1     = row.insertCell(0);
    	var element1  = document.createElement("input");
    	element1.type = "checkbox";
    	cell1.appendChild(element1);

    	var cell2       = row.insertCell(1);
    	cell2.innerHTML = globalLineItemsRowCount; //rowCount + 1;

        var cell3     = row.insertCell(2);
        var element3  = document.createElement("input");
        element3.type = "text";
        element3.name = `order[line_items_attributes][${globalLineItemsRowCount-1}][item]`;
        cell3.appendChild(element3);

        var cell4     = row.insertCell(3);
        var element4  = document.createElement("input");
        element4.type = "text";
        element4.name = `order[line_items_attributes][${globalLineItemsRowCount-1}][quantity]`;
        cell4.appendChild(element4);

        var cell5 = row.insertCell(4);
        var div   = document.createElement("div");
        // div.classList.add("dropdown1");

        // var tf  = document.createElement("input");
        // tf.name = `order[line_items_attributes][${globalLineItemsRowCount-1}][gift_wrap_type]`;
        // tf.classList.add("input");
        // div.appendChild(tf);

        var sel = document.createElement("select");
        sel.name = `order[line_items_attributes][${globalLineItemsRowCount-1}][gift_wrap_type]`;
        sel.classList.add("select");

		var opt;
        var gift_wrap_types = ["Click and select one value", "Plain Paper", "Color Paper"];
		for (var i = 0; i<gift_wrap_types.length; i++) {
	        opt = document.createElement("option");
	        opt.text  = gift_wrap_types[i];
	        sel.appendChild(opt);
		}

        sel.addEventListener("change", updateSelectValue);
        div.appendChild(sel);
        cell5.appendChild(div);

        globalLineItemsRowCount++;

    }
</script>

<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

            <ul>
            <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <table id="dataTableO" border="1">
        <thead>
            <tr>
                <td colspan="2"></td>
                <td>Item</td>
                <td>Quantity </td>
                <td>Gift Wrap Style</td>
            </tr>
        </thead>
        <tbody>
            <% counter = 1 %>
            <%= f.fields_for :line_items do |l| %>
                <tr>
                    <td><input type="checkbox" name="chk"/></td>
                    <td> <%= counter %> </td>
                    <% counter += 1 %>
                    <td> <%= l.text_field   :item %> </td>
                    <td> <%= l.number_field :quantity %> </td>
                    <td> <%= l.select :gift_wrap_type, options_for_select([
                                    ["Click and select one value", "Click and select one value"],
                                    ["Plain Paper", "Plain Paper"],
                                    ["Color Paper", "Color Paper"]
                    ], l.object.gift_wrap_type)
                        %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <div class="flex items-center">
        <button class="bg-blue-700 text-white font-bold" type="button" onclick="addRowToOrders('dataTableO')">
            Add Row
        </button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button class="bg-blue-700 text-white font-bold" type="button" onclick="deleteRow('dataTableO')">
            Delete Row
        </button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <%= f.submit class: "bg-blue-700 text-white font-bold", value: "Create Order" %>
    </div>
<% end %>

app/views/orders/_form.html.erb
<script type="text/javascript">

    function updateSelectValue() {
        this.previousElementSibling.value = this.value;
        this.previousElementSibling.focus();
    }

    function deleteRow(tableID)
    {
    	try
    	{
    		var table = document.getElementById(tableID);
    		var rowCount = table.rows.length;
    		for(var i=0; i<rowCount; i++)
    		{
    			var row = table.rows[i];
    			var chkbox = row.cells[0].childNodes[0];
    			if(null != chkbox && true == chkbox.checked)
    			{
    				table.deleteRow(i);
    				rowCount--;
    				i--;
    			}
    		}
    	}
    	catch(e)
    	{
    		alert(e);
    	}
    }

    var globalLineItemsRowCount = 2;
    function addRowToOrders(tableID)
    {
        var table    = document.getElementById(tableID);
    	var rowCount = table.rows.length;
    	var row      = table.insertRow(rowCount);

        var cell1     = row.insertCell(0);
    	var element1  = document.createElement("input");
    	element1.type = "checkbox";
    	cell1.appendChild(element1);

    	var cell2       = row.insertCell(1);
    	cell2.innerHTML = globalLineItemsRowCount; //rowCount + 1;

        var cell3     = row.insertCell(2);
        var element3  = document.createElement("input");
        element3.type = "text";
        element3.name = `order[line_items_attributes][${globalLineItemsRowCount-1}][item]`;
        cell3.appendChild(element3);

        var cell4     = row.insertCell(3);
        var element4  = document.createElement("input");
        element4.type = "text";
        element4.name = `order[line_items_attributes][${globalLineItemsRowCount-1}][quantity]`;
        cell4.appendChild(element4);

        var cell5 = row.insertCell(4);
        var div   = document.createElement("div");
        // div.classList.add("dropdown1");

        // var tf  = document.createElement("input");
        // tf.name = `order[line_items_attributes][${globalLineItemsRowCount-1}][gift_wrap_type]`;
        // tf.classList.add("input");
        // div.appendChild(tf);

        var sel = document.createElement("select");
        sel.name = `order[line_items_attributes][${globalLineItemsRowCount-1}][gift_wrap_type]`;
        sel.classList.add("select");

		var opt;
        var gift_wrap_types = ["Click and select one value", "Plain Paper", "Color Paper"];
		for (var i = 0; i<gift_wrap_types.length; i++) {
	        opt = document.createElement("option");
	        opt.text  = gift_wrap_types[i];
	        sel.appendChild(opt);
		}

        sel.addEventListener("change", updateSelectValue);
        div.appendChild(sel);
        cell5.appendChild(div);

        globalLineItemsRowCount++;

    }
</script>

<%= form_for(@order) do |f| %>
    <% if @order.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

        <ul>
        <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
        </ul>
    </div>
    <% end %>

    <table id="dataTableO" border="1">
        <thead>
            <tr>
                <td colspan="2"></td>
                <td>Item</td>
                <td>Quantity </td>
                <td>Gift Wrap Style</td>
            </tr>
        </thead>
        <tbody>
            <%= f.fields_for :line_items do |l| %>
                <tr>
                    <td><input type="checkbox" name="chk"/></td>
                    <td>1</td>
                    <td> <%= l.text_field   :item %> </td>
                    <td> <%= l.number_field :quantity %> </td>
                    <td> <%= l.select :gift_wrap_type, options_for_select([
                                    ["Click and select one value", "Click and select one value"],
                                    ["Plain Paper", "Plain Paper"],
                                    ["Color Paper", "Color Paper"]
                                ])
                         %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <div>
    <button type="button" onclick="addRowToOrders('dataTableO')">
        Add Row
    </button>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <button type="button" onclick="deleteRow('dataTableO')">
        Delete Row
    </button>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.submit value: "Create Order" %>
    </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'edit_form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3" scope="col" class="px-6 py-3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order_path(order), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<table>
  <thead>
    <tr>
      <th colspan="3" scope="col" class="px-6 py-3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order.line_items.each do |order| %>
      <tr>
        <td><%= order.item %></td>
        <td><%= order.quantity %></td>
        <td><%= order.gift_wrap_type %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/site/index.html.erb
<div id="root"></div>